### ISSUE TITLE
Sorting Warning

### ISSUE THREAD

**Issue by pjs902** [ClusterMonteCarlo/CMC-COSMIC#46]
Hello,

I've been running a few models and have been pretty consistently getting a warning from the sorting algorithm. As far as I can tell everything else seems to be working fine so I was wondering if this is something I should be concerned about or something that is safe to ignore:

`ERROR: in proc 246: /CMC/CMC-COSMIC/src/cmc/cmc_sort.c:289 in sample(): Oversampling occurred! id = 246 num samples = 1024 local no. of stars = 560`

This was a model with N=2e5, rv=0.5, running on 256 cores.

**Comment by carlrodriguez** [comment]
Hi, this issue occurs if you're running on more cores than there are number of sample sort keys.  By default, there are 1024 sample keys required per core.  The code will still run but will be highly inefficient.

For 2e5 stars, you probably only need 8 or 16 cores.
