### ISSUE TITLE
Segmentation fault encountered while running CMC

### ISSUE THREAD

**Issue by zhang2023-byte** [ClusterMonteCarlo/CMC-COSMIC#54]
Hi, 

I attempted to run CMC on both WSL and a Linux server. The program works fine when I set PERTURB=0, but encounters a segmentation fault when PERTURB=1. I'm not sure what's causing this issue and would appreciate your help. The command line output is attached below. Thank you!

zhang.

(cosmic) zhang@Savior:~/CMC-COSMIC/examples$ mpirun -n 4 ./cmc PlummerSphere.ini plummer
WARNING: parser(): parameter "MASS_PC_BH_INCLUDE" unset: using default value "1").
WARNING: parser(): parameter "WRITE_RWALK_INFO" unset: using default value "0").
WARNING: parser(): parameter "WRITE_MORECOLL_INFO" unset: using default value "0").
WARNING: parser(): parameter "CALCULATE10" unset: using default value "0").
WARNING: parser(): parameter "WIND_FACTOR" unset: using default value "1.0").
WARNING: parser(): parameter "TC_POLYTROPE" unset: using default value "0").
WARNING: parser(): parameter "TC_FACTOR" unset: using default value "1.0").
WARNING: parser(): parameter "COLL_FACTOR" unset: using default value "1.0").
WARNING: parser(): parameter "STAR_AGING_SCHEME" unset: using default value "0").
WARNING: parser(): parameter "PREAGING" unset: using default value "0").
WARNING: parser(): parameter "STREAMS" unset: using default value "1").
WARNING: parser(): parameter "BH_LOSS_CONE" unset: using default value "0").
WARNING: parser(): parameter "MINIMUM_R" unset: using default value "0.0").
WARNING: parser(): parameter "BH_R_DISRUPT_NB" unset: using default value "0.").
WARNING: parser(): parameter "CIRC_PERIOD_THRESHOLD" unset: using default value "1e-18").
WARNING: parser(): parameter "INITIAL_VALUE_DF_INTEGRAND" unset: using default value "0.").
WARNING: parser(): parameter "SEARCH_GRID" unset: using default value "0").
WARNING: parser(): parameter "SG_STARSPERBIN" unset: using default value "100").
WARNING: parser(): parameter "SG_MAXLENGTH" unset: using default value "1000000").
WARNING: parser(): parameter "SG_MINLENGTH" unset: using default value "1000").
WARNING: parser(): parameter "SG_POWER_LAW_EXPONENT" unset: using default value "0.5").
WARNING: parser(): parameter "SG_MATCH_AT_FRACTION" unset: using default value "0.5").
WARNING: parser(): parameter "SG_PARTICLE_FRACTION" unset: using default value "0.95").
WARNING: parser(): parameter "BH_LC_FDT" unset: using default value "0.0").
WARNING: parser(): parameter "APSIDES_PRECISION" unset: using default value "1.0e-11").
WARNING: parser(): parameter "APSIDES_MAX_ITER" unset: using default value "100").
WARNING: parser(): parameter "APSIDES_CONVERGENCE" unset: using default value "5.e-13").
WARNING: parser(): parameter "OVERWRITE_RVIR" unset: using default value "0.").
WARNING: parser(): parameter "OVERWRITE_Z" unset: using default value "0.").
WARNING: parser(): parameter "OVERWRITE_RTID" unset: using default value "0.").
WARNING: parser(): parameter "OVERWRITE_MCLUS" unset: using default value "0.").
WARNING: parser(): parameter "BSE_PTS1_HIGHMASS_CUTOFF" unset: using default value "5").
DIAGNOSTIC: units_set(): METALLICITY= 0.02
DIAGNOSTIC: units_set(): MEGA_YEAR=0.00463304
DIAGNOSTIC: units_set(): SOLAR_MASS_DYN=1
DIAGNOSTIC: units_set(): initial_total_mass=1
DIAGNOSTIC: units_set(): units.t=149098 YEAR
DIAGNOSTIC: units_set(): units.m=10000 MSUN
DIAGNOSTIC: units_set(): units.mstar=1 MSUN
DIAGNOSTIC: units_set(): units.l=1 PARSEC
DIAGNOSTIC: units_set(): units.E=8.55481e+48 erg
DIAGNOSTIC: units_set(): t_rel=2.15841e+08 YEAR
DIAGNOSTIC: load_fits_file_data(): R_disrupt for a solar mass star in NB-units, Rdisr=0
******************************************************************************
tcount=1 TotalTime=0.0000000000000000e+00 Dt=0.0000000000000000e+00
Etotal=-0.25 max_r=0 N_bound=10000 Rtidal=1e+06
Mtotal=1 Etotal.P=-0.5 Etotal.K=0.25 VRatio=1
TidalMassLoss=0
core_radius=0.370305 rho_core=1.12049 v_core=0.842922 Trc=347.429 conc_param=0 N_core=1191.65
trh=0.0938891 rh=0.773554 rh_single=0.773554 rh_binary=0
N_b=0 M_b=0 E_b=0
******************************************************************************
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node Savior exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------

**Comment by carlrodriguez** [comment]
Hi Zhang, without more information it's hard to provide more detailed information.  However, you're running with a relatively small number of particles.  How many MPI processes are you using?  For N=10,000 I would use only a handful (maybe two processes.)

**Comment by zhang2023-byte** [comment]
Hi Carl, 

My issue is unrelated to the number of MPI processes; I have tried various numbers of processes such as 1, 2, 4, 8, etc., while correspondingly increasing the number of stars, but still encountered the same segmentation fault. 

I am running the program in an Ubuntu 22.04 environment, but the problem seems unrelated to the environment since I attempted to run the program using a singularity container and encountered the same segmentation fault. 

How should I proceed with debugging, and what information should I provide to receive more effective assistance from you?

**Comment by zhang2023-byte** [comment]
Hi Carl,

My issue is unrelated to the number of MPI processes; I have tried various numbers of processes such as 1, 2, 4, 8, etc., while correspondingly increasing the number of stars, but still encountered the same segmentation fault.

I am running the program in an Ubuntu 22.04 environment, but the problem seems unrelated to the environment since I attempted to run the program using a singularity container and encountered the same segmentation fault.

How should I proceed with debugging, and what information should I provide to receive more effective assistance from you?

Additional Information:
My issue arises when attempting to run examples from the examples folder after correctly configuring and compiling with CMake according to the instructions provided on the website. I have made no modifications to the executable file cmc or the configuration files (.ini).

2024-02-27 20:44:23"Carl Rodriguez" ***@***.***>写道：

Hi Zhang, without more information it's hard to provide more detailed information. However, you're running with a relatively small number of particles. How many MPI processes are you using? For N=10,000 I would use only a handful (maybe two processes.)

**Comment by zhang2023-byte** [comment]
Problem solved!

The problem might be caused by small OMP_STACKSIZE，which might not be a problem in supercomputer, but for wsl or vertual machine it's better manually configured.

Add the lines

export OMP_STACKSIZE=128M
export OMP_NUM_THREADS=N_threads
ulimit -s unlimited
in the shell configure/initial file (e.g. .bashrc for bash)
