### ISSUE TITLE
Accelerate CMC

### ISSUE THREAD

**Issue by zhang2023-byte** [ClusterMonteCarlo/CMC-COSMIC#57]
I am trying to use CMC to simulate a realistic star cluster with ~1e6 particles. The device is an Intel(R) Xeon(R) Platinum 8280 CPU @ 2.70GHz, but I find the calculation too expensive ~100hours/time. Can you give me some practical suggestions to speed up the calculation?

**Comment by carlrodriguez** [comment]
Hi, how many cores are you running the calculation on?  4 days of wall time for a 1e6 particle cluster, especially if it is a compact (rv = 1pc) cluster, isn't that unreasonable (though with enough cores you could probably get it down to 2-3 days).
