### ISSUE TITLE
generic powerlaw

### ISSUE THREAD

**Issue by scottcoughlin2014** [ClusterMonteCarlo/CMC-COSMIC#6]
@nweatherford 

- Newlin code up piece wise power law sampling of the primary mass, to include kroupa and sal peter as special cases of the generic piecewise power law. and modify to be compatible with Giacomo binary sampling kwarg.
- https://github.com/COSMIC-PopSynth/COSMIC/pull/453

**Comment by carlrodriguez** [comment]
Done
